spring:
  datasource:
    url: jdbc:postgresql://postgresql-orders:5432/orders
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-all-in-one-inmemory-collector:14268/api/traces
