# Default values for coolstore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: coolstore

postgresql:
  image: registry.redhat.io/rhel8/postgresql-13:latest

databases:
  - name: inventory-db
    username: redhat
    password: redhat
  - name: orders-db
    username: redhat
    password: redhat
  - name: customers-db
    username: redhat
    password: redhat

inventory:
  name: inventory
  image: quay.io/openshiftlabs/app-mod-inventory:1.0
  database:
    url: jdbc:postgresql://inventory-db:5432/inventory-db
    username: redhat
    password: redhat
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 512Mi

orders:
  name: orders
  image: quay.io/openshiftlabs/app-mod-orders:1.0
  database:
    url: jdbc:postgresql://orders-db:5432/orders-db
    username: redhat
    password: redhat
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 512Mi

customers:
  name: customers
  image: quay.io/openshiftlabs/app-mod-customers:latest
  database:
    url: jdbc:postgresql://customers-db:5432/customers-db
    username: redhat
    password: redhat
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 512Mi

gateway:
  name: gateway
  image: quay.io/openshiftlabs/app-mod-gateway:1.1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 512Mi

frontend:
  name: frontend
  image: quay.io/openshiftlabs/app-mod-ordersfrontend:1.0
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
