apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: retail
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-mw-demos/app-mod-projects.git
    targetRevision: main
    path: frontend/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: retail
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
