---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    openshift.io/display-name: "Coolstore"
    openshift.io/description: "Coolstore namespace description."
